version: '3.6'
services:
  offloadingserver:
    image: offloadingserver:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "9398"

  offloadingclient:
    image: client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - offloadingserver